<?php
function slugify(string $name): string {
    $slug = mb_strtolower($name, 'UTF-8');
    $slug = str_replace([' ', '&', '-', '.', "'", 'â€™'], ['_', 'and', '_', '', '', ''], $slug);
    while (strpos($slug, '__') !== false) {
        $slug = str_replace('__', '_', $slug);
    }
    return $slug;
}

$teams = [
    'Arsenal' => [
        ['Bukayo', 'Saka', 'Winger'],
        ['Declan', 'Rice', 'Midfielder'],
        ['Gabriel', 'Martinelli', 'Forward'],
        ['Martin', 'Odegaard', 'Midfielder'],
        ['William', 'Saliba', 'Defender'],
        ['Aaron', 'Ramsdale', 'Goalkeeper'],
        ['Ben', 'White', 'Defender'],
        ['Oleksandr', 'Zinchenko', 'Defender'],
    ],
    'Aston Villa' => [
        ['Ollie', 'Watkins', 'Forward'],
        ['Douglas', 'Luiz', 'Midfielder'],
        ['Emi', 'Buendia', 'Attacking Midfielder'],
        ['Tyrone', 'Mings', 'Defender'],
        ['Matty', 'Cash', 'Defender'],
        ['John', 'McGinn', 'Midfielder'],
        ['Marvelous', 'Nakamba', 'Midfielder'],
        ['Lucas', 'Digne', 'Defender'],
    ],
    'Bournemouth' => [
        ['Dominic', 'Solanke', 'Forward'],
        ['Rasmus', 'Hojlund', 'Forward'],
        ['Philip', 'Billing', 'Midfielder'],
        ['Lloyd', 'Kelly', 'Defender'],
        ['Antoine', 'Semenyo', 'Forward'],
        ['Neto', 'Ferreira', 'Goalkeeper'],
        ['Ryan', 'Christie', 'Midfielder'],
        ['Marcus', 'Tavernier', 'Defender'],
    ],
    'Brentford' => [
        ['Ivan', 'Toney', 'Forward'],
        ['Bryan', 'Mbeumo', 'Forward'],
        ['Yoane', 'Wissa', 'Forward'],
        ['Christian', 'Norgaard', 'Midfielder'],
        ['Vitaly', 'Janelt', 'Midfielder'],
        ['Ben', 'Mee', 'Defender'],
        ['Rico', 'Henry', 'Defender'],
        ['Sergi', 'Canos', 'Winger'],
    ],
    'Brighton & Hove Albion' => [
        ['Moises', 'Caicedo', 'Midfielder'],
        ['Kaoru', 'Mitoma', 'Forward'],
        ['Solly', 'March', 'Wingback'],
        ['Lewis', 'Dunk', 'Defender'],
        ['Pervis', 'Estupinan', 'Defender'],
        ['Robert', 'Sanchez', 'Goalkeeper'],
        ['Joel', 'Veltman', 'Defender'],
        ['Simon', 'Adingra', 'Forward'],
    ],
    'Chelsea' => [
        ['Cole', 'Palmer', 'Attacking Midfielder'],
        ['Raheem', 'Sterling', 'Forward'],
        ['Nicolas', 'Jackson', 'Striker'],
        ['Reece', 'James', 'Defender'],
        ['Ben', 'Chilwell', 'Defender'],
        ['Thiago', 'Silva', 'Defender'],
        ['Kepa', 'Arrizabalaga', 'Goalkeeper'],
        ['Conor', 'Gallagher', 'Midfielder'],
    ],
    'Crystal Palace' => [
        ['Eberechi', 'Eze', 'Attacking Midfielder'],
        ['Michael', 'Olise', 'Forward'],
        ['Odsonne', 'Edouard', 'Striker'],
        ['Joachim', 'Andersen', 'Defender'],
        ['Tyrick', 'Mitchell', 'Defender'],
        ['Jordan', 'Ayew', 'Forward'],
        ['Cheick', 'Doucoure', 'Midfielder'],
        ['Vicente', 'Guaita', 'Goalkeeper'],
    ],
    'Everton' => [
        ['James', 'Tarkowski', 'Defender'],
        ['Dominic', 'Calvert-Lewin', 'Forward'],
        ['Amadou', 'Onana', 'Midfielder'],
        ['Idrissa', 'Gueye', 'Midfielder'],
        ['Seamus', 'Coleman', 'Defender'],
        ['Jordan', 'Pickford', 'Goalkeeper'],
        ['Dwight', 'McNeil', 'Midfielder'],
        ['Alex', 'Iwobi', 'Midfielder'],
    ],
    'Fulham' => [
        ['Aleksandar', 'Mitrovic', 'Striker'],
        ['Joao', 'Palhinha', 'Midfielder'],
        ['Bobby', 'Reid', 'Forward'],
        ['Ruben', 'Loftus-Cheek', 'Midfielder'],
        ['Harrison', 'Reed', 'Midfielder'],
        ['Bernd', 'Leno', 'Goalkeeper'],
        ['Tosin', 'Adarabioyo', 'Defender'],
        ['Antonee', 'Robinson', 'Defender'],
    ],
    'Liverpool' => [
        ['Mohamed', 'Salah', 'Forward'],
        ['Virgil', 'van Dijk', 'Defender'],
        ['Trent', 'Alexander-Arnold', 'Defender'],
        ['Andrew', 'Robertson', 'Defender'],
        ['Alisson', 'Becker', 'Goalkeeper'],
        ['Jordan', 'Henderson', 'Midfielder'],
        ['Darwin', 'Nunez', 'Forward'],
        ['Curtis', 'Jones', 'Midfielder'],
    ],
    'Manchester City' => [
        ['Erling', 'Haaland', 'Forward'],
        ['Kevin', 'De Bruyne', 'Midfielder'],
        ['Phil', 'Foden', 'Midfielder'],
        ['Jack', 'Grealish', 'Forward'],
        ['Rodri', 'Hernandez', 'Midfielder'],
        ['Ederson', 'Moraes', 'Goalkeeper'],
        ['Ruben', 'Dias', 'Defender'],
        ['Kyle', 'Walker', 'Defender'],
    ],
    'Manchester United' => [
        ['Marcus', 'Rashford', 'Forward'],
        ['Bruno', 'Fernandes', 'Midfielder'],
        ['Christian', 'Eriksen', 'Midfielder'],
        ['Casemiro', 'da Silva', 'Midfielder'],
        ['Harry', 'Maguire', 'Defender'],
        ['Luke', 'Shaw', 'Defender'],
        ['Diogo', 'Dalot', 'Defender'],
        ['Alejandro', 'Garnacho', 'Forward'],
    ],
    'Newcastle United' => [
        ['Alexander', 'Isak', 'Forward'],
        ['Kieran', 'Trippier', 'Defender'],
        ['Bruno', 'Guimaraes', 'Midfielder'],
        ['Miguel', 'Almiron', 'Forward'],
        ['Nick', 'Pope', 'Goalkeeper'],
        ['Joelinton', 'Santos', 'Midfielder'],
        ['Sven', 'Botman', 'Defender'],
        ['Allan', 'Saint-Maximin', 'Winger'],
    ],
    'Nottingham Forest' => [
        ['Brennan', 'Johnson', 'Winger'],
        ['Morgan', 'Gibbs-White', 'Midfielder'],
        ['Taiwo', 'Awoniyi', 'Forward'],
        ['Neco', 'Williams', 'Defender'],
        ['Joe', 'Worrall', 'Defender'],
        ['Moussa', 'Niakhate', 'Defender'],
        ['Anthony', 'Elanga', 'Forward'],
        ['Ryan', 'Yates', 'Midfielder'],
    ],
    'Tottenham Hotspur' => [
        ['Harry', 'Kane', 'Striker'],
        ['Heung-Min', 'Son', 'Forward'],
        ['James', 'Maddison', 'Midfielder'],
        ['Cristian', 'Romero', 'Defender'],
        ['Destiny', 'Udogie', 'Defender'],
        ['Ivan', 'Perisic', 'Winger'],
        ['Oliver', 'Skipp', 'Midfielder'],
        ['Pierre-Emile', 'Hojbjerg', 'Midfielder'],
    ],
    'West Ham United' => [
        ['Jarrod', 'Bowen', 'Winger'],
        ['Lucas', 'Paqueta', 'Midfielder'],
        ['James', 'Ward-Prowse', 'Midfielder'],
        ['Kurt', 'Zouma', 'Defender'],
        ['Nayef', 'Aguerd', 'Defender'],
        ['Emerson', 'Palmieri', 'Defender'],
        ['Alphonse', 'Areola', 'Goalkeeper'],
        ['Michail', 'Antonio', 'Forward'],
    ],
    'Wolverhampton Wanderers' => [
        ['Matheus', 'Cunha', 'Forward'],
        ['Rayan', 'Ait-Nouri', 'Defender'],
        ['Raul', 'Jimenez', 'Forward'],
        ['Hee-Chan', 'Hwang', 'Forward'],
        ['Nelson', 'Semedo', 'Defender'],
        ['Fabio', 'Silva', 'Forward'],
        ['Maximilian', 'Kilman', 'Defender'],
        ['Jonny', 'Castro', 'Defender'],
    ],
    'Leicester City' => [
        ['Kelechi', 'Iheanacho', 'Forward'],
        ['Kiernan', 'Dewsbury-Hall', 'Midfielder'],
        ['James', 'Justin', 'Defender'],
        ['Youri', 'Tielemans', 'Midfielder'],
        ['Wesley', 'Fofana', 'Defender'],
        ['Wilfred', 'Ndidi', 'Midfielder'],
        ['Daniel', 'Amartey', 'Defender'],
        ['James', 'Maddison', 'Midfielder'],
    ],
    'Ipswich Town' => [
        ['James', 'Norwood', 'Forward'],
        ['Flynn', 'Downes', 'Midfielder'],
        ['Wes', 'Burns', 'Forward'],
        ['Conor', 'Chaplin', 'Forward'],
        ['Leif', 'Davis', 'Defender'],
        ['Aaron', 'Connolly', 'Forward'],
        ['Frankie', 'Kent', 'Defender'],
        ['Tom', 'Clarke', 'Defender'],
    ],
    'Leinster Rugby' => [
        ['Johnny', 'Sexton', 'Fly-half'],
        ['Cian', 'Healy', 'Prop'],
        ['James', 'Ryan', 'Lock'],
        ['Garry', 'Ringrose', 'Centre'],
        ['Robbie', 'Henshaw', 'Centre'],
        ['Caelan', 'Doris', 'Number 8'],
        ['Hugo', 'Keenan', 'Fullback'],
        ['Andrew', 'Porter', 'Prop'],
        ['Ross', 'Byrne', 'Fly-half'],
        ['Dan', 'Sheehan', 'Hooker'],
        ['Jack', 'Conan', 'Number 8'],
        ['Jamison', 'Gibson-Park', 'Scrum-half'],
    ],
    'Saracens' => [
        ['Owen', 'Farrell', 'Fly-half'],
        ['Maro', 'Itoje', 'Lock'],
        ['Billy', 'Vunipola', 'Number 8'],
        ['Alex', 'Goode', 'Fullback'],
        ['Max', 'Malins', 'Wing'],
        ['Nick', 'Tompkins', 'Centre'],
        ['Ben', 'Earl', 'Flanker'],
        ['Jamie', 'George', 'Hooker'],
        ['Elliot', 'Daly', 'Wing'],
        ['Lewis', 'Ludlam', 'Flanker'],
        ['Tom', 'Willis', 'Lock'],
        ['Julian', 'Montoya', 'Hooker'],
    ],
    'Toulouse' => [
        ['Antoine', 'Dupont', 'Scrum-half'],
        ['Romain', 'Ntamack', 'Fly-half'],
        ['Thomas', 'Ramos', 'Fullback'],
        ['Peato', 'Mauvaka', 'Hooker'],
        ['Cheslin', 'Kolbe', 'Wing'],
        ['Cyril', 'Baille', 'Prop'],
        ['Damian', 'Penaud', 'Wing'],
        ['Anthony', 'Jelonch', 'Flanker'],
        ['Francois', 'Cros', 'Lock'],
        ['Teddy', 'Thomas', 'Wing'],
        ['Daniel', 'Berges', 'Lock'],
        ['Thibaud', 'Flament', 'Prop'],
    ],
    'Ulster Rugby' => [
        ['Jacob', 'Stockdale', 'Wing'],
        ['Marcell', 'Coetzee', 'Number 8'],
        ['Iain', 'Henderson', 'Lock'],
        ['Stuart', 'McCloskey', 'Centre'],
        ['John', 'Cooney', 'Scrum-half'],
        ['Darren', 'Cave', 'Centre'],
        ['Jordi', 'Murphy', 'Flanker'],
        ['Will', 'Addison', 'Fullback'],
        ['Eric', 'OSullivan', 'Prop'],
        ['Robert', 'Baloucoune', 'Wing'],
        ['Michael', 'Lowry', 'Fly-half'],
        ['Billy', 'Burns', 'Scrum-half'],
    ],
    'Munster Rugby' => [
        ['Peter', 'OMahony', 'Flanker'],
        ['Conor', 'Murray', 'Scrum-half'],
        ['Joey', 'Carbery', 'Fly-half'],
        ['Tadhg', 'Beirne', 'Lock'],
        ['Andrew', 'Conway', 'Wing'],
        ['Niall', 'Scannell', 'Hooker'],
        ['John', 'Ryan', 'Prop'],
        ['Jeremy', 'Loughman', 'Prop'],
        ['Diarmuid', 'Barron', 'Lock'],
        ['Greg', 'OShea', 'Fullback'],
        ['Alex', 'Nankivell', 'Centre'],
        ['Jack', 'O\'Donnell', 'Back'],
    ],
    'Exeter Chiefs' => [
        ['Sam', 'Simmonds', 'Number 8'],
        ['Joe', 'Simmonds', 'Fly-half'],
        ['Ollie', 'Devoto', 'Centre'],
        ['Jack', 'Nowell', 'Wing'],
        ['Henry', 'Slade', 'Centre'],
        ['Lewis', 'Boyce', 'Prop'],
        ['Archie', 'Hill', 'Halfback'],
        ['Sam', 'Hill', 'Hooker'],
        ['Tom', 'Oakes', 'Prop'],
        ['Jack', 'Yeandle', 'Hooker'],
        ['Cam', 'Kieran', 'Utility'],
        ['Yannick', 'Landsbury', 'Back'],
    ],
    'Northampton Saints' => [
        ['Courtney', 'Lawes', 'Lock'],
        ['Dan', 'Biggar', 'Fly-half'],
        ['Theo', 'Dan', 'Fullback'],
        ['Louis', 'Schreuder', 'Scrum-half'],
        ['Fraser', 'Dingwall', 'Centre'],
        ['Tom', 'Wood', 'Number 8'],
        ['Alex', 'Waller', 'Prop'],
        ['Ollie', 'Lawson', 'Flanker'],
        ['Fin', 'Smith', 'Wing'],
        ['Curwin', 'Bosch', 'Fly-half'],
        ['Mike', 'Haywood', 'Hooker'],
        ['Ahsee', 'Tuite', 'Prop'],
    ],
    'Bath Rugby' => [
        ['Finn', 'Russell', 'Fly-half'],
        ['Semesa', 'Rokoduguni', 'Wing'],
        ['Jonathan', 'Joseph', 'Centre'],
        ['Taulupe', 'Faletau', 'Number 8'],
        ['Charlie', 'Ewels', 'Lock'],
        ['Ruaridh', 'McConnochie', 'Wing'],
        ['Will', 'Muir', 'Wing'],
        ['Max', 'Ojomoh', 'Centre'],
        ['Ben', 'Spencer', 'Scrum-half'],
        ['Tom', 'de Glanville', 'Fly-half'],
        ['D\'Arcy', 'Carden', 'Prop'],
        ['Danny', 'Gray', 'Centre'],
    ],
    'Racing 92' => [
        ['Teddy', 'Thomas', 'Wing'],
        ['Finn', 'Russell', 'Fly-half'],
        ['Simon', 'Zebo', 'Wing'],
        ['Joe', 'Tuisova', 'Wing'],
        ['Demba', 'Bamba', 'Prop'],
        ['Juan', 'Imhoff', 'Wing'],
        ['Maxime', 'Machenaud', 'Scrum-half'],
        ['Baptiste', 'Chouzenoux', 'Flanker'],
        ['Baptiste', 'Gros', 'Lock'],
        ['Lorenzo', 'Cittadini', 'Prop'],
        ['Charles', 'Galea', 'Centre'],
        ['Cameron', 'Winton', 'Back'],
    ],
    'La Rochelle' => [
        ['Gregory', 'Alldritt', 'Number 8'],
        ['Jonathan', 'Danty', 'Centre'],
        ['Cameron', 'Waring', 'Prop'],
        ['Nicolas', 'Jeanjean', 'Wing'],
        ['Uini', 'Atonio', 'Prop'],
        ['Julien', 'Marchand', 'Hooker'],
        ['Seta', 'Tamanivalu', 'Wing'],
        ['Charles', 'Roux', 'Lock'],
        ['Baptiste', 'Serin', 'Scrum-half'],
        ['Yoram', 'Moefana', 'Centre'],
        ['Kevin', 'Graham', 'Lock'],
        ['Tom', 'Escande', 'Back'],
    ],
    'Harlequins' => [
        ['Marcus', 'Smith', 'Fly-half'],
        ['Alex', 'Dombrandt', 'Number 8'],
        ['Danny', 'Care', 'Scrum-half'],
        ['Joe', 'Marler', 'Prop'],
        ['Nick', 'Auterac', 'Prop'],
        ['Danny', 'Gale', 'Hooker'],
        ['Marcus', 'Street', 'Fullback'],
        ['Elliot', 'Millar-Mills', 'Lock'],
        ['Tom', 'Wilmot', 'Flanker'],
        ['Graham', 'Kearney', 'Wing'],
        ['Joe', 'Marchant', 'Centre'],
        ['Danny', 'Gray', 'Centre'],
    ],
    'Glasgow Warriors' => [
        ['Ali', 'Price', 'Scrum-half'],
        ['Adam', 'Hastings', 'Fly-half'],
        ['George', 'Horne', 'Scrum-half'],
        ['Rory', 'Darge', 'Flanker'],
        ['Huw', 'Jones', 'Centre'],
        ['Kyle', 'Steyn', 'Wing'],
        ['Jamie', 'Bhatti', 'Prop'],
        ['Stuart', 'McInally', 'Hooker'],
        ['Grant', 'Harris', 'Lock'],
        ['Tommy', 'Searle', 'Flanker'],
        ['Sione', 'Tuipulotu', 'Centre'],
        ['Cole', 'Beckingham', 'Wing'],
    ],
    'Clermont Auvergne' => [
        ['Wesley', 'Fofana', 'Centre'],
        ['Arthur', 'Iturria', 'Lock'],
        ['Gabin', 'Villiere', 'Wing'],
        ['Damien', 'Penaud', 'Wing'],
        ['Romain', 'Ramos', 'Fly-half'],
        ['Pim', 'Rosenbach', 'Scrum-half'],
        ['Julien', 'Toulze', 'Prop'],
        ['Kevin', 'Yahia', 'Prop'],
        ['Geoffrey', 'Doumayrou', 'Centre'],
        ['Brice', 'Dulin', 'Fullback'],
        ['Arthur', 'Ponzo', 'Flanker'],
        ['Nicolas', 'Gonzalez', 'Wing'],
    ],
    'Edinburgh Rugby' => [
        ['Stuart', 'Hogg', 'Fullback'],
        ['Darcy', 'Graham', 'Wing'],
        ['Cam', 'Redpath', 'Centre'],
        ['Matt', 'Scott', 'Centre'],
        ['Kyle', 'Rowe', 'Wing'],
        ['Sam', 'Skinner', 'Lock'],
        ['Huw', 'Jones', 'Centre'],
        ['Evan', 'Olmstead', 'Lock'],
        ['Ross', 'Braude', 'Hooker'],
        ['Warren', 'Whiteley', 'Flanker'],
        ['Jack', 'Dawson', 'Prop'],
        ['Ben', 'Vellacott', 'Scrum-half'],
    ],
    'Club an der Alster' => [
        ['Tobias', 'Hauke', 'Forward'],
        ['Mats', 'Grambusch', 'Midfielder'],
        ['Oliver', 'Cornelius', 'Forward'],
        ['Franz', 'Bohl', 'Defender'],
        ['Lukas', 'Windfeder', 'Midfielder'],
        ['Paul', 'Dorn', 'Defender'],
        ['Felix', 'Beckmann', 'Forward'],
        ['Jan', 'Hannen', 'Defender'],
    ],
    'SV Kampong' => [
        ['Jip', 'Janssen', 'Forward'],
        ['Menno', 'Oosting', 'Defender'],
        ['Tjep', 'Hoedemakers', 'Forward'],
        ['Terrance', 'Pieters', 'Forward'],
        ['Maurits', 'Visser', 'Midfielder'],
        ['Sander', 'de Wijn', 'Defender'],
        ['Sebastian', 'Brinkman', 'Midfielder'],
        ['Bram', 'Weerman', 'Goalkeeper'],
    ],
    'Rot-Weiss Koln' => [
        ['Oliver', 'Korn', 'Midfielder'],
        ['Martin', 'Zwicker', 'Midfielder'],
        ['Jan-Philipp', 'Rabente', 'Forward'],
        ['Christopher', 'Ross', 'Defender'],
        ['Benedikt', 'Sturm', 'Defender'],
        ['Alexander', 'Johansen', 'Forward'],
        ['Timo', 'Wierckx', 'Forward'],
        ['Philipp', 'Zeller', 'Defender'],
    ],
    'HC Den Bosch' => [
        ['Billy', 'Bakker', 'Forward'],
        ['Jeroen', 'Hertzberger', 'Forward'],
        ['Roel', 'Bovendeert', 'Forward'],
        ['Mirco', 'Pruijser', 'Forward'],
        ['Tim', 'Herman', 'Midfielder'],
        ['Nico', 'Koeper', 'Defender'],
        ['Sebastiaan', 'Vellinga', 'Goalkeeper'],
        ['Lucas', 'Wierenga', 'Midfielder'],
    ],
    'Atletico de Madrid HC' => [
        ['Santi', 'Freixa', 'Forward'],
        ['Rodrigo', 'Garcia', 'Midfielder'],
        ['Pablo', 'Amat', 'Defender'],
        ['Dani', 'Martin', 'Forward'],
        ['Eric', 'Moreno', 'Defender'],
        ['Carlos', 'Garcia', 'Goalkeeper'],
        ['Jorge', 'Serra', 'Defender'],
        ['Pau', 'Cunill', 'Forward'],
    ],
    'RC Polo Barcelona' => [
        ['Pau', 'Cunill', 'Forward'],
        ['Xavi', 'Tecsa', 'Midfielder'],
        ['Aleix', 'Agut', 'Defender'],
        ['Tomas', 'Gubbe', 'Midfielder'],
        ['Marc', 'Sierra', 'Forward'],
        ['Marc', 'Revolta', 'Defender'],
        ['Pol', 'Gonzalez', 'Goalkeeper'],
        ['Joan', 'Garcia', 'Forward'],
    ],
    'Oranje Zwart' => [
        ['Jelle', 'Galema', 'Forward'],
        ['Pirmin', 'Blaak', 'Goalkeeper'],
        ['Tim', 'Swaen', 'Defender'],
        ['Sebastiaan', 'Vijani', 'Midfielder'],
        ['Bob', 'de Voogd', 'Forward'],
        ['Laurens', 'van der Steen', 'Defender'],
        ['Jip', 'van der Linden', 'Forward'],
        ['Timo', 'de Bakker', 'Defender'],
    ],
    'Beeston HC' => [
        ['Sam', 'Ward', 'Forward'],
        ['Danny', 'Chitters', 'Forward'],
        ['Ben', 'Booth', 'Midfielder'],
        ['Will', 'Duchare', 'Defender'],
        ['Harry', 'Charles', 'Defender'],
        ['Alex', 'Hodgson', 'Goalkeeper'],
        ['Josh', 'Brown', 'Midfielder'],
        ['James', 'Bridges', 'Defender'],
    ],
    'Trentino Itas' => [
        ['Earvin', "N'Gapeth", 'Outside Hitter'],
        ['Matt', 'Anderson', 'Outside Hitter'],
        ['Simone', 'Giannelli', 'Setter'],
        ['Osmany', 'Juantorena', 'Outside Hitter'],
        ['Yury', 'Berezhko', 'Opposite'],
        ['Aleksander', 'Atanasijevic', 'Opposite'],
        ['Vladimir', 'Grachyov', 'Middle Blocker'],
        ['Lorenzo', 'Cappellini', 'Libero'],
    ],
    'Zenit Kazan' => [
        ['Maxim', 'Mikhaylov', 'Opposite'],
        ['Earvin', "N'Gapeth", 'Outside Hitter'],
        ['Wilfredo', 'Leon', 'Outside Hitter'],
        ['Marko', 'Ivovic', 'Opposite'],
        ['Alexey', 'Verbov', 'Setter'],
        ['Dmitry', 'Muserskiy', 'Middle Blocker'],
        ['Evgeny', 'Sivozhelez', 'Setter'],
        ['Denis', 'Kudryavtsev', 'Middle Blocker'],
    ],
    'Zaksa Kedzierzyn' => [
        ['Wilfredo', 'Leon', 'Outside Hitter'],
        ['Bartosz', 'Kurek', 'Opposite'],
        ['Mateusz', 'Bieniek', 'Middle Blocker'],
        ['Aleksander', 'Swiderski', 'Outside Hitter'],
        ['Damian', 'Schulz', 'Outside Hitter'],
        ['Jakub', 'Bednorz', 'Outside Hitter'],
        ['David', 'Smith', 'Setter'],
        ['Lukas', 'Kaczmarek', 'Opposite'],
    ],
    'Sir Safety Perugia' => [
        ['Simone', 'Giannelli', 'Setter'],
        ['Osmany', 'Juantorena', 'Outside Hitter'],
        ['Wilfredo', 'Leon', 'Outside Hitter'],
        ['Filippo', 'Lanza', 'Outside Hitter'],
        ['Earvin', "N'Gapeth", 'Opposite'],
        ['Mateusz', 'Bazanski', 'Libero'],
        ['Max', 'Holz', 'Middle Blocker'],
        ['Robert', 'Landers', 'Middle Blocker'],
    ],
    'Lube Civitanova' => [
        ['Osmany', 'Juantorena', 'Outside Hitter'],
        ['Luciano', 'De Cecco', 'Setter'],
        ['Filippo', 'Lanza', 'Outside Hitter'],
        ['Simone', 'Parodi', 'Outside Hitter'],
        ['Matteo', 'Piano', 'Middle Blocker'],
        ['Milan', 'Panic', 'Opposite'],
        ['Robert', 'Kaiser', 'Middle Blocker'],
        ['Dino', 'Perin', 'Libero'],
    ],
    'Modena Volley' => [
        ['Fabio', 'Balaso', 'Setter'],
        ['Nemanja', 'Petric', 'Outside Hitter'],
        ['Oleh', 'Plotnytskyi', 'Outside Hitter'],
        ['Valerio', 'Vikoli', 'Middle Blocker'],
        ['Gabriele', 'Nelli', 'Middle Blocker'],
        ['Giovanni', 'Sanguinetti', 'Libero'],
        ['Leandro', 'Mosca', 'Opposite'],
        ['Lorenzo', 'Cappellini', 'Outside Hitter'],
    ],
    'Halkbank Ankara' => [
        ['Ivan', 'Zaytsev', 'Opposite'],
        ['Simon', 'Halk', 'Outside Hitter'],
        ['Mert', 'Aydin', 'Middle Blocker'],
        ['Cagatay', 'Kirmizi', 'Setter'],
        ['Volkan', 'Uslan', 'Libero'],
        ['Alican', 'Cetin', 'Receiver'],
        ['Deniz', 'Aydin', 'Opposite'],
        ['Karol', 'Klech', 'Middle Blocker'],
    ],
    'Dinamo Moscow' => [
        ['Evandro', 'Guerra', 'Outside Hitter'],
        ['Dmitry', 'Muserskiy', 'Middle Blocker'],
        ['Ivan', 'Zaytsev', 'Opposite'],
        ['Alexander', 'Volkov', 'Opposite'],
        ['Igor', 'Krasilnikov', 'Outside Hitter'],
        ['Anton', 'Slioussar', 'Libero'],
        ['Artem', 'Volvich', 'Middle Blocker'],
        ['Alexey', 'Verbov', 'Setter'],
    ],
    'AVE Novy Bor' => [
        ['David', 'Navara', 'Grandmaster'],
        ['Michal', 'Krasenkow', 'Grandmaster'],
        ['Petr', 'Neuman', 'Grandmaster'],
        ['Viktor', 'Laznicka', 'Grandmaster'],
        ['Jakub', 'Mala', 'Grandmaster'],
        ['Jan', 'Krejci', 'Grandmaster'],
    ],
    'Baden-Baden SC' => [
        ['Fabiano', 'Caruana', 'Grandmaster'],
        ['Maxime', 'Vachier-Lagrave', 'Grandmaster'],
        ['Rasmus', 'Svane', 'Grandmaster'],
        ['Vincent', 'Keymer', 'Grandmaster'],
        ['Arkadij', 'Naiditsch', 'Grandmaster'],
        ['Mathias', 'Bluebaum', 'Grandmaster'],
    ],
    'Cercle Echecs Paris' => [
        ['Laurent', 'Fressinet', 'Grandmaster'],
        ['Jules', 'Moussard', 'Grandmaster'],
        ['Romain', 'Edouard', 'Grandmaster'],
        ['Etienne', 'Bacrot', 'Grandmaster'],
        ['Maxime', 'Vachier-Lagrave', 'Grandmaster'],
        ['Jean-Marc', 'Degraeve', 'Grandmaster'],
    ],
    'SOCAR Azerbaijan' => [
        ['Shakhriyar', 'Mamedyarov', 'Grandmaster'],
        ['Rauf', 'Mamedov', 'Grandmaster'],
        ['Eltaj', 'Safarli', 'Grandmaster'],
        ['Teimour', 'Radjabov', 'Grandmaster'],
        ['Anton', 'Korobov', 'Grandmaster'],
        ['Nijat', 'Abasov', 'Grandmaster'],
    ],
    'Istanbul BBSK' => [
        ['Anish', 'Giri', 'Grandmaster'],
        ['Alexander', 'Donchenko', 'Grandmaster'],
        ['Wesley', 'So', 'Grandmaster'],
        ['Emre', 'Can', 'Grandmaster'],
        ['Veselin', 'Topalov', 'Grandmaster'],
        ['Mikhail', 'Antipov', 'Grandmaster'],
    ],
    'Alkaloid Skopje' => [
        ['Alexei', 'Shirov', 'Grandmaster'],
        ['Ivan', 'Cheparinov', 'Grandmaster'],
        ['Kiril', 'Georgiev', 'Grandmaster'],
        ['Vesko', 'Spasov', 'Grandmaster'],
        ['Bogdan', 'Dimitrov', 'Grandmaster'],
        ['Stanislav', 'Pelekov', 'Grandmaster'],
    ],
    'Tops International Stables' => [
        ['Scott', 'Brash', 'Rider'],
        ['Kent', 'Farrington', 'Rider'],
        ['McLain', 'Ward', 'Rider'],
        ['Beezie', 'Madden', 'Rider'],
        ['Laura', 'Kraut', 'Rider'],
    ],
    'Stephex Stables' => [
        ['Kevin', 'Staut', 'Rider'],
        ['Pieter', 'Devos', 'Rider'],
        ['Gregory', 'Wathelet', 'Rider'],
        ['Olivier', 'Philippaerts', 'Rider'],
        ['Constant', 'Van Paesschen', 'Rider'],
    ],
    'Beerbaum Stables' => [
        ['Ludger', 'Beerbaum', 'Rider'],
        ['Meredith', 'Michaels-Beerbaum', 'Rider'],
        ['Marcus', 'Ehning', 'Rider'],
        ['Christian', 'Ahlmann', 'Rider'],
        ['Daniel', 'Deusser', 'Rider'],
    ],
    'McLain Ward Stable' => [
        ['McLain', 'Ward', 'Rider'],
        ['Jessica', 'Springsteen', 'Rider'],
        ['Kent', 'Farrington', 'Rider'],
        ['Jaime', 'Azcarraga', 'Rider'],
        ['Quinn', 'Freeman', 'Rider'],
    ],
    'Spruce Meadows Team' => [
        ['Eric', 'Lamaze', 'Rider'],
        ['Beezie', 'Madden', 'Rider'],
        ['Kent', 'Farrington', 'Rider'],
        ['Tiffany', 'Foster', 'Rider'],
        ['Mario', 'Deslauriers', 'Rider'],
    ],
    'Abu Dhabi Equestrian' => [
        ['Ali', 'Al-Thani', 'Rider'],
        ['Khalid', 'Al-Mubarak', 'Rider'],
        ['Justine', 'Munnings', 'Rider'],
        ['Penelope', 'Leprevost', 'Rider'],
        ['Nolan', 'Davis', 'Rider'],
    ],
    'Li-Ning Badminton Club' => [
        ['Kento', 'Momota', 'Singles'],
        ['Tai', 'Tzu-ying', 'Singles'],
        ['Viktor', 'Axelsen', 'Singles'],
        ['Carolina', 'Marin', 'Singles'],
    ],
    'Yonex Japan Club' => [
        ['Akane', 'Yamaguchi', 'Singles'],
        ['Nozomi', 'Okuhara', 'Singles'],
        ['Kento', 'Momota', 'Singles'],
        ['Yuta', 'Watanabe', 'Doubles'],
    ],
    'Victor Korea Club' => [
        ['Lee', 'Zii Jia', 'Singles'],
        ['An', 'Se-young', 'Singles'],
        ['Heo', 'Kwang-hee', 'Singles'],
        ['Kim', 'Ga-eun', 'Singles'],
    ],
    'Djarum Kudus' => [
        ['Anthony', 'Ginting', 'Singles'],
        ['Gregoria', 'Mariska', 'Tunjung'],
        ['Jonatan', 'Christie', 'Singles'],
        ['Kevin', 'Sukamuljo', 'Doubles'],
    ],
    'PB Djarum' => [
        ['Marcus', 'Gideon', 'Doubles'],
        ['Kevin', 'Sukamuljo', 'Doubles'],
        ['Greysia', 'Polii', 'Doubles'],
        ['Apriyani', 'Rahayu', 'Doubles'],
    ],
    'Performa Badminton' => [
        ['Carolina', 'Marin', 'Singles'],
        ['Viktor', 'Axelsen', 'Singles'],
        ['Chen', 'Long', 'Singles'],
        ['Wang', 'Yihan', 'Singles'],
    ],
    'Feng Tian Badminton' => [
        ['Chen', 'Long', 'Singles'],
        ['Li', 'Xuerui', 'Singles'],
        ['Wang', 'Yihan', 'Singles'],
        ['Zhang', 'Ning', 'Singles'],
    ],
    'Badminton England Elite' => [
        ['Marcus', 'Ellis', 'Doubles'],
        ['Ben', 'Lane', 'Doubles'],
        ['Chloe', 'Birch', 'Doubles'],
        ['Sean', 'Vendy', 'Singles'],
    ],
];

$insertLines = [];
foreach ($teams as $team => $players) {
    $teamSlug = slugify($team);
    foreach ($players as $player) {
        [$first, $last, $position] = $player;
        $emailFirst = mb_strtolower(str_replace(' ', '_', str_replace(['Ã©','Ã¡','Ã­','Ã³','Ã±','â€™',"'"], ['e','a','i','o','n','',''], $first)), 'UTF-8');
        $emailLast = mb_strtolower(str_replace([' ', '-', 'Ã©','Ã¡','Ã­','Ã³','Ã±','â€™',"'"], ['_','_','e','a','i','o','n','',''], $last), 'UTF-8');
        $email = "$emailFirst.$emailLast@$teamSlug.apexsportsclub.local";
        $address = "$team Training Ground";
        if (strpos($team, 'Rugby') !== false || in_array($team, ['Leinster Rugby','Saracens','Toulouse','Ulster Rugby','Munster Rugby','Exeter Chiefs','Northampton Saints','Bath Rugby','Racing 92','La Rochelle','Harlequins','Glasgow Warriors','Clermont Auvergne','Edinburgh Rugby'])) {
            $sportId = 1;
        } elseif (in_array($team, ['Club an der Alster','SV Kampong','Rot-Weiss Koln','HC Den Bosch','Atletico de Madrid HC','RC Polo Barcelona','Oranje Zwart','Beeston HC'])) {
            $sportId = 3;
        } elseif (in_array($team, ['Trentino Itas','Zenit Kazan','Zaksa Kedzierzyn','Sir Safety Perugia','Lube Civitanova','Modena Volley','Halkbank Ankara','Dinamo Moscow'])) {
            $sportId = 4;
        } elseif (in_array($team, ['AVE Novy Bor','Baden-Baden SC','Cercle Echecs Paris','SOCAR Azerbaijan','Istanbul BBSK','Alkaloid Skopje'])) {
            $sportId = 5;
        } elseif (strpos($team, 'Stable') !== false || strpos($team, 'Stables') !== false || strpos($team, 'Equestrian') !== false) {
            $sportId = 6;
        } elseif (strpos($team, 'Badminton') !== false || strpos($team, 'Club') !== false || strpos($team, 'Yonex') !== false || strpos($team, 'Victor') !== false || strpos($team, 'Djarum') !== false) {
            $sportId = 7;
        } else {
            $sportId = 2;
        }
        $insertLines[] = sprintf(
            '(\'%s\', \'%s\', \'%s\', \'$2y$10$abcdefghijklmnopqrstuvwxyza1234567890123456789012345678901234567890\', \'071-000-0000\', \'%s\', %d, 1, \'%s\')',
            addslashes($first),
            addslashes($last),
            addslashes($email),
            addslashes($address),
            $sportId,
            addslashes($position)
        );
    }
}

$sql = "-- Migration 033: Seed fuller real rosters for every existing team.\n\n";
$sql .= "DELETE tm\nFROM team_memberships tm\nJOIN members m ON tm.member_id = m.member_id\nWHERE m.email LIKE '%@%.apexsportsclub.local';\n\n";
$sql .= "DELETE FROM members\nWHERE email LIKE '%@%.apexsportsclub.local';\n\n";
$sql .= "INSERT INTO members (`first_name`, `last_name`, `email`, `password`, `phone_number`, `address`, `sport_id`, `show_in_directory`, `position`) VALUES\n";
$sql .= implode(",\n", $insertLines) . ";\n\n";
$sql .= "INSERT IGNORE INTO team_memberships (`league_id`, `team_id`, `member_id`, `role`, `status`)\n";
$sql .= "SELECT t.league_id, t.team_id, m.member_id, 'Player', 'Active'\n";
$sql .= "FROM teams t\n";
$sql .= "JOIN members m ON m.email LIKE CONCAT('%@', LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(t.name, ' ', '_'), '&', 'and'), '-', '_'), '.', ''), '''', '')), '.apexsportsclub.local')\n";
$sql .= "WHERE m.email LIKE '%@%.apexsportsclub.local';\n";

file_put_contents(__DIR__ . '/../migrations/033_seed_full_team_rosters.sql', $sql);
echo "Generated migrations/033_seed_full_team_rosters.sql with " . count($insertLines) . " members\n";

